export type AnnotatedLine = {
  line: number
  code: string
  note: string
}

export type AnnotatedFile = {
  id: 'tsx' | 'css'
  filename: string
  language: string
  lines: AnnotatedLine[]
}

export const ANNOTATED_FILES: AnnotatedFile[] = [
  {
    id: 'tsx',
    filename: 'Material3BottomSheetDemo.tsx',
    language: 'TypeScript / React',
    lines: [
      { line: 1, code: "import { useCallback, useEffect, useRef, useState } from 'react'", note: '引入 React Hooks：状态、副作用、持久引用、稳定回调' },
      { line: 2, code: "import { ANNOTATED_FILES, type AnnotatedFile } from './annotatedCode'", note: '引入逐行备注数据类型与 ANNOTATED_FILES 常量' },
      { line: 3, code: "", note: '空行，分隔 import 与常量' },
      { line: 4, code: "const DISMISS_THRESHOLD = 120", note: '拖拽超过 120px 时判定为「应该关闭」' },
      { line: 5, code: "const DISMISS_VELOCITY = 0.8", note: '快速下滑速度阈值；甩动关闭时用这个判断' },
      { line: 6, code: "", note: '空行' },
      { line: 7, code: "type DragState = {", note: '定义拖拽过程的临时数据结构' },
      { line: 8, code: "  startY: number", note: '手指/鼠标按下时的 Y 坐标' },
      { line: 9, code: "  offset: number", note: '开始拖拽时面板已有的下移距离' },
      { line: 10, code: "  dragging: boolean", note: '当前是否处于拖拽中' },
      { line: 11, code: "}", note: '类型定义结束' },
      { line: 12, code: "", note: '空行' },
      { line: 13, code: "function CodeAnnotator({ file }: { file: AnnotatedFile }) {", note: 'CodeAnnotator 子组件：渲染带逐行中文备注的源码列表' },
      { line: 14, code: "  return (", note: 'return 开始' },
      { line: 15, code: "    <div className=\"m3-code-viewer\">", note: '代码阅读器外层容器' },
      { line: 16, code: "      <p className=\"m3-code-viewer__filename\">{file.filename}</p>", note: '显示当前文件名（如 Material3BottomSheetDemo.tsx）' },
      { line: 17, code: "      <ol className=\"m3-code-lines\">", note: '有序列表，一行源码对应一个 li' },
      { line: 18, code: "        {file.lines.map((entry) => (", note: '遍历 file.lines，为每行生成列表项' },
      { line: 19, code: "          <li key={`${file.id}-${entry.line}`} className=\"m3-code-line\">", note: '列表项 key，避免切换文件时 React 复用错乱' },
      { line: 20, code: "            <div className=\"m3-code-line__row\">", note: '行号 + 代码 的横向网格行' },
      { line: 21, code: "              <span className=\"m3-code-line__number\">{entry.line}</span>", note: '左侧行号' },
      { line: 22, code: "              <pre className=\"m3-code-line__code\">", note: '右侧代码 pre 块' },
      { line: 23, code: "                <code>{entry.code || ' '}</code>", note: '代码文本；空行用空格占位避免塌陷' },
      { line: 24, code: "              </pre>", note: 'pre 结束' },
      { line: 25, code: "            </div>", note: '网格行结束' },
      { line: 26, code: "            <p className=\"m3-code-line__note\">{entry.note}</p>", note: '该行对应的中文说明' },
      { line: 27, code: "          </li>", note: '列表项结束' },
      { line: 28, code: "        ))}", note: 'map 回调结束' },
      { line: 29, code: "      </ol>", note: 'ol 结束' },
      { line: 30, code: "    </div>", note: 'viewer 容器结束' },
      { line: 31, code: "  )", note: '组件 return 结束' },
      { line: 32, code: "}", note: 'CodeAnnotator 组件定义结束' },
      { line: 33, code: "", note: '空行' },
      { line: 34, code: "export default function Material3BottomSheetDemo() {", note: '导出页面主组件，整个 demo 的入口' },
      { line: 35, code: "  const [open, setOpen] = useState(false)", note: '控制抽屉是否打开；false=隐藏，true=显示' },
      { line: 36, code: "  const [closing, setClosing] = useState(false)", note: '控制关闭动画；true 时面板滑回屏幕外' },
      { line: 37, code: "  const [dragOffset, setDragOffset] = useState(0)", note: '面板被拖下去多少像素；传给 CSS 变量控制位移' },
      { line: 38, code: "  const [dragging, setDragging] = useState(false)", note: '是否正在拖拽；用于关闭 CSS 过渡，实现跟手' },
      { line: 39, code: "  const [activeFileId, setActiveFileId] = useState<'tsx' | 'css'>('tsx')", note: '当前查看的源码文件：tsx 或 css' },
      { line: 40, code: "  const dragRef = useRef<DragState>({ startY: 0, offset: 0, dragging: false })", note: '拖拽中间值放 ref，避免频繁 re-render' },
      { line: 41, code: "  const lastMoveRef = useRef({ y: 0, t: 0 })", note: '记录上一次指针位置和时间，用来算甩动速度' },
      { line: 42, code: "", note: '空行' },
      { line: 43, code: "  const activeFile = ANNOTATED_FILES.find((file) => file.id === activeFileId)!", note: '根据 activeFileId 从 ANNOTATED_FILES 取出当前文件' },
      { line: 44, code: "", note: '空行' },
      { line: 45, code: "  const close = useCallback(() => {", note: '封装关闭逻辑，供多处复用' },
      { line: 46, code: "    setClosing(true)", note: '先触发关闭动画 class（面板滑出）' },
      { line: 47, code: "    setDragOffset(0)", note: '重置拖拽偏移，避免下次打开位置不对' },
      { line: 48, code: "    window.setTimeout(() => {", note: '等关闭动画播完（200ms）再真正卸载' },
      { line: 49, code: "      setOpen(false)", note: '抽屉从 DOM 逻辑上关闭，遮罩消失' },
      { line: 50, code: "      setClosing(false)", note: '复位关闭状态，方便下次再开' },
      { line: 51, code: "    }, 200)", note: '200ms 对应 CSS 里关闭动效时长 short4' },
      { line: 52, code: "  }, [])", note: 'useCallback 依赖为空，函数地址稳定' },
      { line: 53, code: "", note: '空行' },
      { line: 54, code: "  const openSheet = () => {", note: '点击「打开源码备注」按钮时调用' },
      { line: 55, code: "    setClosing(false)", note: '确保打开时走「进入动画」而不是关闭动画' },
      { line: 56, code: "    setDragOffset(0)", note: '从底部原位置弹起，不带残留偏移' },
      { line: 57, code: "    setOpen(true)", note: '显示遮罩和面板，触发 CSS 滑入' },
      { line: 58, code: "  }", note: '打开函数结束' },
      { line: 59, code: "", note: '空行' },
      { line: 60, code: "  useEffect(() => {", note: '抽屉打开时注册键盘和滚动锁定' },
      { line: 61, code: "    if (!open) return", note: '没打开就不做任何事' },
      { line: 62, code: "", note: '空行' },
      { line: 63, code: "    const onKeyDown = (event: KeyboardEvent) => {", note: '监听键盘事件' },
      { line: 64, code: "      if (event.key === 'Escape') close()", note: '按 Esc 关闭抽屉' },
      { line: 65, code: "    }", note: '键盘回调结束' },
      { line: 66, code: "", note: '空行' },
      { line: 67, code: "    const previousOverflow = document.body.style.overflow", note: '记住打开前页面能不能滚动' },
      { line: 68, code: "    document.body.style.overflow = 'hidden'", note: '锁住背景页面，防止后面内容跟着滚' },
      { line: 69, code: "    window.addEventListener('keydown', onKeyDown)", note: '挂上 Esc 监听' },
      { line: 70, code: "", note: '空行' },
      { line: 71, code: "    return () => {", note: '抽屉关闭或组件卸载时清理' },
      { line: 72, code: "      document.body.style.overflow = previousOverflow", note: '恢复背景页面滚动' },
      { line: 73, code: "      window.removeEventListener('keydown', onKeyDown)", note: '移除 Esc 监听，防止内存泄漏' },
      { line: 74, code: "    }", note: '清理函数结束' },
      { line: 75, code: "  }, [open, close])", note: 'open 或 close 变化时重新执行 effect' },
      { line: 76, code: "", note: '空行' },
      { line: 77, code: "  const onPointerDown = (event: React.PointerEvent<HTMLDivElement>) => {", note: '在拖动手柄上按下时触发' },
      { line: 78, code: "    dragRef.current = {", note: '记录本次拖拽起点信息' },
      { line: 79, code: "      startY: event.clientY,", note: '按下时的屏幕 Y 坐标' },
      { line: 80, code: "      offset: dragOffset,", note: '如果已经拖下去一点，从这里继续算' },
      { line: 81, code: "      dragging: true,", note: '标记开始拖拽' },
      { line: 82, code: "    }", note: 'dragRef 赋值结束' },
      { line: 83, code: "    setDragging(true)", note: '通知 React：进入拖拽态，CSS 去掉 transition' },
      { line: 84, code: "    lastMoveRef.current = { y: event.clientY, t: performance.now() }", note: '初始化速度计算采样点' },
      { line: 85, code: "    event.currentTarget.setPointerCapture(event.pointerId)", note: '把后续 move/up 事件锁定到手柄，拖出区域也能跟手' },
      { line: 86, code: "  }", note: 'pointerdown 结束' },
      { line: 87, code: "", note: '空行' },
      { line: 88, code: "  const onPointerMove = (event: React.PointerEvent<HTMLDivElement>) => {", note: '手指/鼠标移动时触发' },
      { line: 89, code: "    if (!dragRef.current.dragging) return", note: '没在拖拽就直接忽略' },
      { line: 90, code: "", note: '空行' },
      { line: 91, code: "    const delta = event.clientY - dragRef.current.startY", note: '相对按下点移动了多少' },
      { line: 92, code: "    const nextOffset = Math.max(0, dragRef.current.offset + delta)", note: '只允许向下拖，不能拖到负数（往上飞）' },
      { line: 93, code: "    setDragOffset(nextOffset)", note: '更新面板下移距离，屏幕实时跟手' },
      { line: 94, code: "    lastMoveRef.current = { y: event.clientY, t: performance.now() }", note: '持续更新速度采样' },
      { line: 95, code: "  }", note: 'pointermove 结束' },
      { line: 96, code: "", note: '空行' },
      { line: 97, code: "  const onPointerUp = (event: React.PointerEvent<HTMLDivElement>) => {", note: '松手时决定关闭还是回弹' },
      { line: 98, code: "    if (!dragRef.current.dragging) return", note: '没在拖拽就忽略' },
      { line: 99, code: "", note: '空行' },
      { line: 100, code: "    dragRef.current.dragging = false", note: '结束拖拽状态' },
      { line: 101, code: "    setDragging(false)", note: '恢复 CSS 过渡，用于回弹或关闭动画' },
      { line: 102, code: "", note: '空行' },
      { line: 103, code: "    const now = performance.now()", note: '当前时间戳' },
      { line: 104, code: "    const dt = Math.max(now - lastMoveRef.current.t, 1)", note: '距上次移动过了多少毫秒，防除零' },
      { line: 105, code: "    const velocity = (event.clientY - lastMoveRef.current.y) / dt", note: '估算松手瞬间的下滑速度' },
      { line: 106, code: "", note: '空行' },
      { line: 107, code: "    const shouldDismiss =", note: '判断该不该关' },
      { line: 108, code: "      dragOffset > DISMISS_THRESHOLD || velocity > DISMISS_VELOCITY", note: '拖得够远 或 甩得够快 → 关闭' },
      { line: 109, code: "", note: '空行' },
      { line: 110, code: "    if (shouldDismiss) {", note: '满足关闭条件' },
      { line: 111, code: "      close()", note: '走关闭动画并隐藏抽屉' },
      { line: 112, code: "      return", note: '不再回弹' },
      { line: 113, code: "    }", note: '关闭分支结束' },
      { line: 114, code: "", note: '空行' },
      { line: 115, code: "    setDragOffset(0)", note: '没关成就弹回原位' },
      { line: 116, code: "  }", note: 'pointerup 结束' },
      { line: 117, code: "", note: '空行' },
      { line: 118, code: "  return (", note: '开始渲染页面 JSX' },
      { line: 119, code: "    <div className=\"m3-demo\">", note: '整页容器，控制 demo 背景布局' },
      { line: 120, code: "      <header className=\"m3-demo__header\">", note: '顶部标题区域' },
      { line: 121, code: "        <p className=\"m3-demo__eyebrow\">Material Design 3</p>", note: '眉题小字，说明设计体系' },
      { line: 122, code: "        <h1 className=\"m3-demo__title\">半屏 Bottom Sheet</h1>", note: '页面主标题' },
      { line: 123, code: "        <p className=\"m3-demo__subtitle\">", note: '副标题开始' },
      { line: 124, code: "          打开抽屉可查看本页源码，每行都标注了控制什么。", note: '说明打开抽屉可查看带备注的源码' },
      { line: 125, code: "        </p>", note: '副标题结束' },
      { line: 126, code: "      </header>", note: '头部结束' },
      { line: 127, code: "", note: '空行' },
      { line: 128, code: "      <main className=\"m3-demo__content\">", note: '主内容区，放触发按钮' },
      { line: 129, code: "        <button type=\"button\" className=\"m3-filled-button\" onClick={openSheet}>", note: 'M3 填充按钮，点击打开抽屉' },
      { line: 130, code: "          打开源码备注", note: '按钮文字' },
      { line: 131, code: "        </button>", note: '按钮结束' },
      { line: 132, code: "", note: '空行' },
      { line: 133, code: "        <p className=\"m3-demo__hint\">", note: '操作提示区域' },
      { line: 134, code: "          抽屉内可切换 TSX / CSS 两个文件，上下滚动阅读逐行备注。", note: '说明抽屉内可切换 TSX/CSS 并滚动阅读' },
      { line: 135, code: "          <br />", note: '换行' },
      { line: 136, code: "          线上地址：<code>/demo.html</code>", note: '开发/线上访问路径提示' },
      { line: 137, code: "        </p>", note: '提示结束' },
      { line: 138, code: "      </main>", note: '主内容结束' },
      { line: 139, code: "", note: '空行' },
      { line: 140, code: "      <div", note: '抽屉根节点开始；始终挂在 DOM，靠 class 控制显隐' },
      { line: 141, code: "        className={`m3-sheet-root${open ? ' is-open' : ''}`}", note: 'open 时加 is-open，允许点击并显示动画' },
      { line: 142, code: "        aria-hidden={!open}", note: '没打开时告诉读屏器忽略这层' },
      { line: 143, code: "      >", note: '根节点标签结束' },
      { line: 144, code: "        <button", note: '遮罩层；用 button 是为了可键盘聚焦' },
      { line: 145, code: "          type=\"button\"", note: '普通按钮，不提交表单' },
      { line: 146, code: "          className={`m3-sheet-scrim${dragging ? ' is-dragging' : ''}`}", note: '遮罩样式；拖拽时去掉淡入淡出过渡' },
      { line: 147, code: "          aria-label=\"关闭抽屉\"", note: '无障碍：说明点击可关闭' },
      { line: 148, code: "          onClick={close}", note: '点遮罩关闭抽屉' },
      { line: 149, code: "          tabIndex={open ? 0 : -1}", note: '只有打开时才能 Tab 聚焦到遮罩' },
      { line: 150, code: "        />", note: '遮罩自闭合' },
      { line: 151, code: "", note: '空行' },
      { line: 152, code: "        <div", note: '真正的抽屉面板开始' },
      { line: 153, code: "          role=\"dialog\"", note: '语义：这是一个对话框' },
      { line: 154, code: "          aria-modal=\"true\"", note: '语义：打开时用户应聚焦在此层' },
      { line: 155, code: "          aria-labelledby=\"sheet-title\"", note: '关联标题，读屏器会朗读标题' },
      { line: 156, code: "          className={`m3-sheet-panel${dragging ? ' is-dragging' : ''}${closing ? ' is-closing' : ''}`}", note: '面板样式；拖拽/关闭时切换不同动画 class' },
      { line: 157, code: "          style={{ '--sheet-drag-offset': `${dragOffset}px` } as React.CSSProperties}", note: '把 JS 算出的拖拽距离传给 CSS 变量' },
      { line: 158, code: "        >", note: '面板标签结束' },
      { line: 159, code: "          <div", note: '拖动手柄区域开始' },
      { line: 160, code: "            className=\"m3-sheet-handle\"", note: '手柄容器样式（居中、padding、grab 光标）' },
      { line: 161, code: "            aria-hidden", note: '装饰性元素，读屏器跳过' },
      { line: 162, code: "            onPointerDown={onPointerDown}", note: '在这里按下开始拖拽' },
      { line: 163, code: "            onPointerMove={onPointerMove}", note: '在这里移动更新面板位置' },
      { line: 164, code: "            onPointerUp={onPointerUp}", note: '在这里松手决定关闭或回弹' },
      { line: 165, code: "            onPointerCancel={onPointerUp}", note: '系统打断手势时，按松手处理' },
      { line: 166, code: "          >", note: '手柄容器标签结束' },
      { line: 167, code: "            <span className=\"m3-sheet-handle__bar\" />", note: '那根 32×4 的灰色横条' },
      { line: 168, code: "          </div>", note: '手柄区域结束' },
      { line: 169, code: "", note: '空行' },
      { line: 170, code: "          <div className=\"m3-sheet-header\">", note: '抽屉标题区' },
      { line: 171, code: "            <h2 id=\"sheet-title\" className=\"m3-sheet-header__title\">", note: '标题文字；id 供 aria-labelledby 引用' },
      { line: 172, code: "              源码逐行备注", note: '抽屉内容标题' },
      { line: 173, code: "            </h2>", note: '标题结束' },
      { line: 174, code: "            <p className=\"m3-sheet-header__subtitle\">", note: '副标题开始' },
      { line: 175, code: "              {activeFile.language} · 半屏可滚动", note: '显示当前文件语言与抽屉高度说明' },
      { line: 176, code: "            </p>", note: '副标题结束' },
      { line: 177, code: "          </div>", note: '标题区结束' },
      { line: 178, code: "", note: '空行' },
      { line: 179, code: "          <div className=\"m3-code-tabs\" role=\"tablist\" aria-label=\"源码文件\">", note: 'TSX/CSS 文件切换 Tab 容器' },
      { line: 180, code: "            {ANNOTATED_FILES.map((file) => (", note: '遍历 ANNOTATED_FILES 生成 Tab 按钮' },
      { line: 181, code: "              <button", note: 'Tab 按钮开始' },
      { line: 182, code: "                key={file.id}", note: 'React key' },
      { line: 183, code: "                type=\"button\"", note: '普通按钮' },
      { line: 184, code: "                role=\"tab\"", note: 'ARIA role：选项卡' },
      { line: 185, code: "                aria-selected={activeFileId === file.id}", note: '当前选中 Tab 标记为 selected' },
      { line: 186, code: "                className={`m3-code-tab${activeFileId === file.id ? ' is-active' : ''}`}", note: 'Tab 样式；选中时加 is-active' },
      { line: 187, code: "                onClick={() => setActiveFileId(file.id)}", note: '点击切换到对应源码文件' },
      { line: 188, code: "              >", note: 'Tab 按钮内容开始' },
      { line: 189, code: "                {file.filename}", note: '显示文件名' },
      { line: 190, code: "              </button>", note: 'Tab 按钮结束' },
      { line: 191, code: "            ))}", note: 'map 结束' },
      { line: 192, code: "          </div>", note: 'Tab 列表结束' },
      { line: 193, code: "", note: '空行' },
      { line: 194, code: "          <div className=\"m3-sheet-body\">", note: '抽屉可滚动内容区' },
      { line: 195, code: "            <CodeAnnotator file={activeFile} />", note: '渲染当前选中文件的逐行备注' },
      { line: 196, code: "          </div>", note: '内容区结束' },
      { line: 197, code: "", note: '空行' },
      { line: 198, code: "          <div className=\"m3-sheet-actions\">", note: '底部操作按钮区' },
      { line: 199, code: "            <button type=\"button\" className=\"m3-text-button\" onClick={close}>", note: '文字按钮「关闭」' },
      { line: 200, code: "              关闭", note: '关闭按钮文案' },
      { line: 201, code: "            </button>", note: '关闭按钮结束' },
      { line: 202, code: "          </div>", note: '操作区结束' },
      { line: 203, code: "        </div>", note: '面板结束' },
      { line: 204, code: "      </div>", note: '抽屉根节点结束' },
      { line: 205, code: "    </div>", note: '整页容器结束' },
      { line: 206, code: "  )", note: 'return 结束' },
      { line: 207, code: "}", note: '组件函数结束' }
    ],
  },
  {
    id: 'css',
    filename: 'material3-bottom-sheet.css',
    language: 'CSS',
    lines: [
      { line: 1, code: '/* Material Design 3 — Bottom Sheet demo tokens (light theme) */', note: '文件说明：M3 浅色主题设计变量' },
      { line: 2, code: '', note: '空行' },
      { line: 3, code: ':root {', note: '全局 CSS 变量，全页复用' },
      { line: 4, code: '  --md-sys-color-primary: #6750a4;', note: '主色：按钮、强调文字' },
      { line: 5, code: '  --md-sys-color-on-primary: #ffffff;', note: '主色上的文字颜色' },
      { line: 6, code: '  --md-sys-color-primary-container: #eaddff;', note: '主色容器背景（本 demo 未直接用）' },
      { line: 7, code: '  --md-sys-color-on-primary-container: #21005d;', note: '主色容器上的文字色' },
      { line: 8, code: '  --md-sys-color-surface: #fef7ff;', note: '页面背景色' },
      { line: 9, code: '  --md-sys-color-on-surface: #1d1b20;', note: '背景上的主文字色' },
      { line: 10, code: '  --md-sys-color-on-surface-variant: #49454f;', note: '次要文字色：副标题、备注' },
      { line: 11, code: '  --md-sys-color-surface-container-low: #f7f2fa;', note: '抽屉面板背景色' },
      { line: 12, code: '  --md-sys-color-surface-container-high: #ece6f0;', note: '代码块、列表项背景' },
      { line: 13, code: '  --md-sys-color-outline: #79747e;', note: '描边/手柄横条颜色' },
      { line: 14, code: '  --md-sys-color-outline-variant: #cac4d0;', note: '弱描边色（备用）' },
      { line: 15, code: '  --md-sys-color-scrim: #000000;', note: '遮罩用的基础黑色' },
      { line: 16, code: '', note: '空行' },
      { line: 17, code: '  --md-sys-shape-corner-extra-large-top: 28px;', note: '抽屉顶部圆角，M3 规范 28dp' },
      { line: 18, code: '  --md-sys-motion-duration-medium2: 300ms;', note: '进入动画时长' },
      { line: 19, code: '  --md-sys-motion-duration-short4: 200ms;', note: '关闭动画时长' },
      { line: 20, code: '  --md-sys-motion-easing-emphasized-decelerate: cubic-bezier(0.05, 0.7, 0.1, 1);', note: '进入缓动：快起慢停' },
      { line: 21, code: '  --md-sys-motion-easing-emphasized-accelerate: cubic-bezier(0.3, 0, 0.8, 0.15);', note: '关闭缓动：慢起快收' },
      { line: 22, code: '}', note: ':root 结束' },
      { line: 23, code: '', note: '空行' },
      { line: 24, code: '* {', note: '全局盒模型重置' },
      { line: 25, code: '  box-sizing: border-box;', note: 'padding/border 算进宽高，布局更可控' },
      { line: 26, code: '}', note: '全局重置结束' },
      { line: 27, code: '', note: '空行' },
      { line: 28, code: 'html,', note: '页面根元素组选择器开始' },
      { line: 29, code: 'body,', note: 'body 参与 100% 高度' },
      { line: 30, code: '#root {', note: 'React 挂载点' },
      { line: 31, code: '  margin: 0;', note: '去掉默认外边距' },
      { line: 32, code: '  min-height: 100%;', note: '至少铺满一屏' },
      { line: 33, code: '  height: 100%;', note: '高度撑满，方便内部 flex 布局' },
      { line: 34, code: '}', note: '根元素组结束' },
      { line: 35, code: '', note: '空行' },
      { line: 36, code: 'body {', note: '页面基础字体和背景' },
      { line: 37, code: '  font-family: Roboto, system-ui, -apple-system, sans-serif;', note: 'M3 默认字体栈' },
      { line: 38, code: '  background: var(--md-sys-color-surface);', note: '整页背景色' },
      { line: 39, code: '  color: var(--md-sys-color-on-surface);', note: '默认文字颜色' },
      { line: 40, code: '  -webkit-font-smoothing: antialiased;', note: '字体抗锯齿，更清晰' },
      { line: 41, code: '}', note: 'body 结束' },
      { line: 42, code: '', note: '空行' },
      { line: 43, code: '.m3-demo {', note: 'demo 页面主容器' },
      { line: 44, code: '  min-height: 100%;', note: '占满视口高度' },
      { line: 45, code: '  display: flex;', note: '启用 flex 纵向排版' },
      { line: 46, code: '  flex-direction: column;', note: '头-内容竖着排' },
      { line: 47, code: '}', note: '.m3-demo 结束' },
      { line: 48, code: '', note: '空行' },
      { line: 49, code: '.m3-demo__header {', note: '顶部标题区内边距' },
      { line: 50, code: '  padding: 24px 24px 16px;', note: '上24 左右24 下16' },
      { line: 51, code: '}', note: 'header 结束' },
      { line: 52, code: '', note: '空行' },
      { line: 53, code: '.m3-demo__eyebrow {', note: '眉题样式' },
      { line: 54, code: '  margin: 0 0 8px;', note: '只留底部 8px 间距' },
      { line: 55, code: '  font-size: 12px;', note: '小字号' },
      { line: 56, code: '  font-weight: 500;', note: '中等字重' },
      { line: 57, code: '  letter-spacing: 0.5px;', note: '字间距，标签感' },
      { line: 58, code: '  color: var(--md-sys-color-on-surface-variant);', note: '次要色' },
      { line: 59, code: '  text-transform: uppercase;', note: '全大写' },
      { line: 60, code: '}', note: '眉题结束' },
      { line: 61, code: '', note: '空行' },
      { line: 62, code: '.m3-demo__title {', note: '主标题样式' },
      { line: 63, code: '  margin: 0 0 8px;', note: '标题下留 8px' },
      { line: 64, code: '  font-size: 28px;', note: '大标题字号' },
      { line: 65, code: '  line-height: 36px;', note: '标题行高' },
      { line: 66, code: '  font-weight: 400;', note: 'M3 标题常用 regular' },
      { line: 67, code: '}', note: '主标题结束' },
      { line: 68, code: '', note: '空行' },
      { line: 69, code: '.m3-demo__subtitle {', note: '副标题样式' },
      { line: 70, code: '  margin: 0;', note: '去掉默认 margin' },
      { line: 71, code: '  font-size: 14px;', note: '副标题字号' },
      { line: 72, code: '  line-height: 20px;', note: '副标题行高' },
      { line: 73, code: '  color: var(--md-sys-color-on-surface-variant);', note: '灰色说明文字' },
      { line: 74, code: '}', note: '副标题结束' },
      { line: 75, code: '', note: '空行' },
      { line: 76, code: '.m3-demo__content {', note: '按钮和提示所在区域' },
      { line: 77, code: '  flex: 1;', note: '占据 header 下方剩余空间' },
      { line: 78, code: '  padding: 0 24px 32px;', note: '左右留白，底部 32px' },
      { line: 79, code: '  display: flex;', note: '内部竖排' },
      { line: 80, code: '  flex-direction: column;', note: '按钮在上，提示在下' },
      { line: 81, code: '  gap: 12px;', note: '子元素间距 12px' },
      { line: 82, code: '}', note: 'content 结束' },
      { line: 83, code: '', note: '空行' },
      { line: 84, code: '.m3-filled-button {', note: 'M3 实心按钮样式' },
      { line: 85, code: '  appearance: none;', note: '去掉系统默认按钮外观' },
      { line: 86, code: '  border: none;', note: '无边框' },
      { line: 87, code: '  border-radius: 999px;', note: '全圆角胶囊按钮' },
      { line: 88, code: '  padding: 10px 24px;', note: '按钮内边距' },
      { line: 89, code: '  font: 500 14px/20px Roboto, sans-serif;', note: '按钮字体' },
      { line: 90, code: '  background: var(--md-sys-color-primary);', note: '紫色主色背景' },
      { line: 91, code: '  color: var(--md-sys-color-on-primary);', note: '白字' },
      { line: 92, code: '  cursor: pointer;', note: '鼠标变手型' },
      { line: 93, code: '  align-self: flex-start;', note: '按钮宽度随内容，不拉满' },
      { line: 94, code: '  transition: box-shadow var(--md-sys-motion-duration-short4)', note: '阴影过渡时长' },
      { line: 95, code: '    var(--md-sys-motion-easing-emphasized-decelerate);', note: '阴影过渡曲线' },
      { line: 96, code: '}', note: '实心按钮结束' },
      { line: 97, code: '', note: '空行' },
      { line: 98, code: '.m3-filled-button:hover {', note: '桌面悬停态' },
      { line: 99, code: '  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px 1px rgba(0, 0, 0, 0.15);', note: '悬停浮起阴影' },
      { line: 100, code: '}', note: 'hover 结束' },
      { line: 101, code: '', note: '空行' },
      { line: 102, code: '.m3-filled-button:active {', note: '按下态' },
      { line: 103, code: '  transform: scale(0.98);', note: '轻微缩小，模拟按压' },
      { line: 104, code: '}', note: 'active 结束' },
      { line: 105, code: '', note: '空行' },
      { line: 106, code: '.m3-demo__hint {', note: '页面底部灰色提示框' },
      { line: 107, code: '  margin: 8px 0 0;', note: '与按钮间距' },
      { line: 108, code: '  padding: 12px 16px;', note: '提示框内边距' },
      { line: 109, code: '  border-radius: 12px;', note: '圆角卡片感' },
      { line: 110, code: '  background: var(--md-sys-color-surface-container-low);', note: '浅紫灰背景' },
      { line: 111, code: '  font-size: 13px;', note: '提示文字大小' },
      { line: 112, code: '  line-height: 18px;', note: '提示行高' },
      { line: 113, code: '  color: var(--md-sys-color-on-surface-variant);', note: '次要文字色' },
      { line: 114, code: '}', note: 'hint 结束' },
      { line: 115, code: '', note: '空行' },
      { line: 116, code: '.m3-demo__hint code {', note: '提示里行内代码样式' },
      { line: 117, code: '  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;', note: '等宽字体' },
      { line: 118, code: '  font-size: 12px;', note: '代码略小' },
      { line: 119, code: '}', note: 'hint code 结束' },
      { line: 120, code: '', note: '空行' },
      { line: 121, code: '/* Bottom sheet overlay */', note: '以下开始是抽屉相关样式' },
      { line: 122, code: '.m3-sheet-root {', note: '抽屉总容器，盖在全屏最上层' },
      { line: 123, code: '  position: fixed;', note: '固定定位，不随页面滚' },
      { line: 124, code: '  inset: 0;', note: '上下左右贴满视口' },
      { line: 125, code: '  z-index: 1000;', note: '层级很高，压住页面内容' },
      { line: 126, code: '  pointer-events: none;', note: '默认关闭时不可点击，避免挡页面' },
      { line: 127, code: '}', note: 'sheet root 结束' },
      { line: 128, code: '', note: '空行' },
      { line: 129, code: '.m3-sheet-root.is-open {', note: '抽屉打开时' },
      { line: 130, code: '  pointer-events: auto;', note: '允许点击遮罩和面板' },
      { line: 131, code: '}', note: 'is-open 结束' },
      { line: 132, code: '', note: '空行' },
      { line: 133, code: '.m3-sheet-scrim {', note: '半透明黑色遮罩' },
      { line: 134, code: '  position: absolute;', note: '相对 sheet-root 定位' },
      { line: 135, code: '  inset: 0;', note: '遮罩铺满全屏' },
      { line: 136, code: '  background: var(--md-sys-color-scrim);', note: '黑色底' },
      { line: 137, code: '  opacity: 0;', note: '默认完全透明（关闭态）' },
      { line: 138, code: '  transition: opacity var(--md-sys-motion-duration-medium2)', note: '遮罩淡入时长 300ms' },
      { line: 139, code: '    var(--md-sys-motion-easing-emphasized-decelerate);', note: '遮罩淡入曲线' },
      { line: 140, code: '}', note: 'scrim 结束' },
      { line: 141, code: '', note: '空行' },
      { line: 142, code: '.m3-sheet-root.is-open .m3-sheet-scrim {', note: '打开时遮罩可见' },
      { line: 143, code: '  opacity: 0.32;', note: 'M3 规范：32% 黑色蒙层' },
      { line: 144, code: '}', note: '打开遮罩结束' },
      { line: 145, code: '', note: '空行' },
      { line: 146, code: '.m3-sheet-scrim.is-dragging {', note: '拖拽时遮罩不做过渡' },
      { line: 147, code: '  transition: none;', note: '去掉 transition，跟手不延迟' },
      { line: 148, code: '}', note: 'dragging scrim 结束' },
      { line: 149, code: '', note: '空行' },
      { line: 150, code: '.m3-sheet-panel {', note: '底部抽屉面板本体' },
      { line: 151, code: '  position: absolute;', note: '绝对定位在屏幕底部' },
      { line: 152, code: '  left: 0;', note: '左边贴边' },
      { line: 153, code: '  right: 0;', note: '右边贴边' },
      { line: 154, code: '  bottom: 0;', note: '底边贴屏幕底' },
      { line: 155, code: '  display: flex;', note: '面板内部竖排：手柄-标题-内容-按钮' },
      { line: 156, code: '  flex-direction: column;', note: '纵向 flex' },
      { line: 157, code: '  max-height: 50vh;', note: '半屏关键：最高只占 50% 视口高度' },
      { line: 158, code: '  background: var(--md-sys-color-surface-container-low);', note: '面板背景色' },
      { line: 159, code: '  border-top-left-radius: var(--md-sys-shape-corner-extra-large-top);', note: '左上 28px 圆角' },
      { line: 160, code: '  border-top-right-radius: var(--md-sys-shape-corner-extra-large-top);', note: '右上 28px 圆角' },
      { line: 161, code: '  box-shadow:', note: '面板浮起阴影开始' },
      { line: 162, code: '    0 4px 8px 3px rgba(0, 0, 0, 0.15),', note: '一层柔和阴影' },
      { line: 163, code: '    0 1px 3px rgba(0, 0, 0, 0.3);', note: '一层近处阴影' },
      { line: 164, code: '  transform: translateY(100%);', note: '默认整面板藏在屏幕下方' },
      { line: 165, code: '  transition: transform var(--md-sys-motion-duration-medium2)', note: '滑入动画 300ms' },
      { line: 166, code: '    var(--md-sys-motion-easing-emphasized-decelerate);', note: '滑入缓动曲线' },
      { line: 167, code: '  will-change: transform;', note: '提前告诉浏览器要动画 transform，更顺滑' },
      { line: 168, code: '  touch-action: none;', note: '减少浏览器默认手势干扰拖拽' },
      { line: 169, code: '}', note: 'panel 结束' },
      { line: 170, code: '', note: '空行' },
      { line: 171, code: '.m3-sheet-root.is-open .m3-sheet-panel {', note: '打开后的面板位置' },
      { line: 172, code: '  transform: translateY(var(--sheet-drag-offset, 0px));', note: '滑上来；拖拽时加上额外下移距离' },
      { line: 173, code: '}', note: '打开 panel 结束' },
      { line: 174, code: '', note: '空行' },
      { line: 175, code: '.m3-sheet-panel.is-dragging {', note: '正在拖拽面板' },
      { line: 176, code: '  transition: none;', note: '去掉过渡，手指拖多少动多少' },
      { line: 177, code: '}', note: 'dragging panel 结束' },
      { line: 178, code: '', note: '空行' },
      { line: 179, code: '.m3-sheet-panel.is-closing {', note: '关闭动画态' },
      { line: 180, code: '  transition: transform var(--md-sys-motion-duration-short4)', note: '关闭动画 200ms' },
      { line: 181, code: '    var(--md-sys-motion-easing-emphasized-accelerate);', note: '关闭更快收回去' },
      { line: 182, code: '  transform: translateY(100%) !important;', note: '强制滑回屏幕外' },
      { line: 183, code: '}', note: 'closing 结束' },
      { line: 184, code: '', note: '空行' },
      { line: 185, code: '.m3-sheet-handle {', note: '顶部拖动手柄区域' },
      { line: 186, code: '  flex: 0 0 auto;', note: '高度固定，不被内容挤扁' },
      { line: 187, code: '  display: flex;', note: '让横条居中' },
      { line: 188, code: '  justify-content: center;', note: '横条水平居中' },
      { line: 189, code: '  padding: 16px 0 8px;', note: '手柄区上下留白' },
      { line: 190, code: '  cursor: grab;', note: '鼠标显示可抓取' },
      { line: 191, code: '}', note: 'handle 结束' },
      { line: 192, code: '', note: '空行' },
      { line: 193, code: '.m3-sheet-handle:active {', note: '正在抓取' },
      { line: 194, code: '  cursor: grabbing;', note: '鼠标变成抓取中' },
      { line: 195, code: '}', note: 'handle active 结束' },
      { line: 196, code: '', note: '空行' },
      { line: 197, code: '.m3-sheet-handle__bar {', note: '那根灰色小横条' },
      { line: 198, code: '  width: 32px;', note: '宽 32px，符合 M3' },
      { line: 199, code: '  height: 4px;', note: '高 4px' },
      { line: 200, code: '  border-radius: 999px;', note: '两头圆' },
      { line: 201, code: '  background: var(--md-sys-color-outline);', note: '灰色' },
      { line: 202, code: '}', note: 'handle bar 结束' },
      { line: 203, code: '', note: '空行' },
      { line: 204, code: '.m3-sheet-header {', note: '抽屉标题区内边距' },
      { line: 205, code: '  padding: 0 24px 8px;', note: '左右 24，下 8' },
      { line: 206, code: '}', note: 'header 结束' },
      { line: 207, code: '', note: '空行' },
      { line: 208, code: '.m3-sheet-header__title {', note: '抽屉标题文字' },
      { line: 209, code: '  margin: 0;', note: '去默认 margin' },
      { line: 210, code: '  font-size: 22px;', note: '标题字号' },
      { line: 211, code: '  line-height: 28px;', note: '标题行高' },
      { line: 212, code: '  font-weight: 400;', note: '字重 regular' },
      { line: 213, code: '}', note: 'title 结束' },
      { line: 214, code: '', note: '空行' },
      { line: 215, code: '.m3-sheet-header__subtitle {', note: '抽屉副标题' },
      { line: 216, code: '  margin: 4px 0 0;', note: '标题下 4px' },
      { line: 217, code: '  font-size: 14px;', note: '副标题字号' },
      { line: 218, code: '  line-height: 20px;', note: '副标题行高' },
      { line: 219, code: '  color: var(--md-sys-color-on-surface-variant);', note: '灰色' },
      { line: 220, code: '}', note: 'subtitle 结束' },
      { line: 221, code: '', note: '空行' },
      { line: 222, code: '.m3-sheet-body {', note: '抽屉中间可滚动区域' },
      { line: 223, code: '  flex: 1;', note: '占满标题和按钮之间剩余高度' },
      { line: 224, code: '  overflow-y: auto;', note: '内容超出就竖向滚动' },
      { line: 225, code: '  padding: 8px 24px 24px;', note: '内容区内边距' },
      { line: 226, code: '  -webkit-overflow-scrolling: touch;', note: 'iOS 惯性滚动更顺' },
      { line: 227, code: '}', note: 'body 结束' },
      { line: 228, code: '', note: '空行' },
      { line: 229, code: '.m3-sheet-actions {', note: '底部按钮区' },
      { line: 230, code: '  display: flex;', note: '横向排按钮' },
      { line: 231, code: '  gap: 8px;', note: '按钮间距' },
      { line: 232, code: '  padding: 8px 24px calc(16px + env(safe-area-inset-bottom, 0px));', note: '底部留出 iPhone 安全区' },
      { line: 233, code: '}', note: 'actions 结束' },
      { line: 234, code: '', note: '空行' },
      { line: 235, code: '.m3-text-button {', note: '文字按钮样式' },
      { line: 236, code: '  appearance: none;', note: '去系统默认样式' },
      { line: 237, code: '  border: none;', note: '无边框' },
      { line: 238, code: '  border-radius: 999px;', note: '胶囊形点击区域' },
      { line: 239, code: '  padding: 10px 12px;', note: '内边距' },
      { line: 240, code: '  font: 500 14px/20px Roboto, sans-serif;', note: '字体' },
      { line: 241, code: '  background: transparent;', note: '透明底' },
      { line: 242, code: '  color: var(--md-sys-color-primary);', note: '紫色文字' },
      { line: 243, code: '  cursor: pointer;', note: '手型光标' },
      { line: 244, code: '}', note: 'text button 结束' },
      { line: 245, code: '', note: '空行' },
      { line: 246, code: '.m3-text-button:hover {', note: '文字按钮悬停' },
      { line: 247, code: '  background: color-mix(in srgb, var(--md-sys-color-primary) 8%, transparent);', note: '淡紫色 hover 底' },
      { line: 248, code: '}', note: 'text hover 结束' },
      { line: 249, code: '', note: '空行' },
      { line: 250, code: '@media (min-width: 600px) {', note: '平板/桌面断点' },
      { line: 251, code: '  .m3-sheet-panel {', note: '大屏下面板不再全宽' },
      { line: 252, code: '    left: 50%;', note: '先移到中间' },
      { line: 253, code: '    right: auto;', note: '取消右贴边' },
      { line: 254, code: '    width: min(100%, 480px);', note: '最大宽 480px' },
      { line: 255, code: '    transform: translate(-50%, 100%);', note: '水平居中 + 藏在底部' },
      { line: 256, code: '  }', note: '大屏 panel 基础态结束' },
      { line: 257, code: '', note: '空行' },
      { line: 258, code: '  .m3-sheet-root.is-open .m3-sheet-panel {', note: '大屏打开态' },
      { line: 259, code: '    transform: translate(-50%, var(--sheet-drag-offset, 0px));', note: '居中显示并支持拖拽偏移' },
      { line: 260, code: '  }', note: '大屏 open 结束' },
      { line: 261, code: '', note: '空行' },
      { line: 262, code: '  .m3-sheet-panel.is-closing {', note: '大屏关闭态' },
      { line: 263, code: '    transform: translate(-50%, 100%) !important;', note: '居中前提下收回底部' },
      { line: 264, code: '  }', note: '大屏 closing 结束' },
      { line: 265, code: '}', note: '媒体查询结束' },
      { line: 267, code: ".m3-code-tabs {", note: '文件切换 Tab 栏容器' },
      { line: 268, code: "  display: flex;", note: '横向 flex 排列 Tab' },
      { line: 269, code: "  gap: 8px;", note: 'Tab 之间间距 8px' },
      { line: 270, code: "  padding: 0 16px 8px;", note: '左右内边距，底部 8px' },
      { line: 271, code: "  overflow-x: auto;", note: 'Tab 过多时可横向滚动' },
      { line: 272, code: "  -webkit-overflow-scrolling: touch;", note: 'iOS 惯性滚动更顺' },
      { line: 273, code: "}", note: 'Tab 栏结束' },
      { line: 274, code: "", note: '空行' },
      { line: 275, code: ".m3-code-tab {", note: '单个文件 Tab 按钮样式' },
      { line: 276, code: "  appearance: none;", note: '去掉系统默认按钮外观' },
      { line: 277, code: "  border: 1px solid var(--md-sys-color-outline-variant);", note: '浅灰描边' },
      { line: 278, code: "  border-radius: 999px;", note: '胶囊形圆角' },
      { line: 279, code: "  padding: 8px 12px;", note: 'Tab 内边距' },
      { line: 280, code: "  font: 500 12px/16px ui-monospace, SFMono-Regular, Menlo, monospace;", note: '等宽小字号字体' },
      { line: 281, code: "  background: transparent;", note: '透明背景' },
      { line: 282, code: "  color: var(--md-sys-color-on-surface-variant);", note: '未选中时次要文字色' },
      { line: 283, code: "  cursor: pointer;", note: '手型光标' },
      { line: 284, code: "  white-space: nowrap;", note: '文件名不换行' },
      { line: 285, code: "  flex: 0 0 auto;", note: '宽度随内容，不被 flex 压缩' },
      { line: 286, code: "}", note: 'Tab 基础样式结束' },
      { line: 287, code: "", note: '空行' },
      { line: 288, code: ".m3-code-tab.is-active {", note: '当前选中的 Tab' },
      { line: 289, code: "  background: var(--md-sys-color-primary-container);", note: '主色容器背景高亮' },
      { line: 290, code: "  border-color: transparent;", note: '选中时去掉边框' },
      { line: 291, code: "  color: var(--md-sys-color-on-primary-container);", note: '选中态深紫文字' },
      { line: 292, code: "}", note: '选中 Tab 结束' },
      { line: 293, code: "", note: '空行' },
      { line: 294, code: ".m3-code-viewer {", note: '代码阅读器外层容器' },
      { line: 295, code: "  display: flex;", note: '纵向 flex 布局' },
      { line: 296, code: "  flex-direction: column;", note: '纵向排列' },
      { line: 297, code: "  gap: 8px;", note: '子元素间距 8px' },
      { line: 298, code: "}", note: 'viewer 结束' },
      { line: 299, code: "", note: '空行' },
      { line: 300, code: ".m3-code-viewer__filename {", note: '文件名标签样式' },
      { line: 301, code: "  margin: 0;", note: '去掉默认 margin' },
      { line: 302, code: "  font: 500 11px/16px ui-monospace, SFMono-Regular, Menlo, monospace;", note: '等宽 11px 文件名文字' },
      { line: 303, code: "  color: var(--md-sys-color-on-surface-variant);", note: '次要灰色' },
      { line: 304, code: "}", note: 'filename 结束' },
      { line: 305, code: "", note: '空行' },
      { line: 306, code: ".m3-code-lines {", note: '源码行列表（ol）' },
      { line: 307, code: "  margin: 0;", note: '去掉列表默认 margin' },
      { line: 308, code: "  padding: 0;", note: '去掉列表默认 padding' },
      { line: 309, code: "  list-style: none;", note: '去掉序号圆点' },
      { line: 310, code: "  display: flex;", note: '纵向 flex' },
      { line: 311, code: "  flex-direction: column;", note: '纵向排列' },
      { line: 312, code: "  gap: 10px;", note: '每行卡片间距 10px' },
      { line: 313, code: "}", note: 'lines 结束' },
      { line: 314, code: "", note: '空行' },
      { line: 315, code: ".m3-code-line {", note: '单行源码卡片' },
      { line: 316, code: "  border-radius: 12px;", note: '圆角 12px' },
      { line: 317, code: "  background: var(--md-sys-color-surface-container-high);", note: '浅灰卡片背景' },
      { line: 318, code: "  padding: 8px 10px;", note: '卡片内边距' },
      { line: 319, code: "}", note: 'line 卡片结束' },
      { line: 320, code: "", note: '空行' },
      { line: 321, code: ".m3-code-line__row {", note: '行号 + 代码 网格行' },
      { line: 322, code: "  display: grid;", note: 'grid 布局' },
      { line: 323, code: "  grid-template-columns: 2.5rem minmax(0, 1fr);", note: '左 2.5rem 行号，右自适应代码' },
      { line: 324, code: "  gap: 8px;", note: '列间距 8px' },
      { line: 325, code: "  align-items: start;", note: '顶部对齐' },
      { line: 326, code: "}", note: 'row 结束' },
      { line: 327, code: "", note: '空行' },
      { line: 328, code: ".m3-code-line__number {", note: '行号样式' },
      { line: 329, code: "  font: 500 11px/18px ui-monospace, SFMono-Regular, Menlo, monospace;", note: '等宽 11px 紫色行号' },
      { line: 330, code: "  color: var(--md-sys-color-primary);", note: '主色强调' },
      { line: 331, code: "  text-align: right;", note: '右对齐' },
      { line: 332, code: "  user-select: none;", note: '行号不可选中' },
      { line: 333, code: "}", note: 'number 结束' },
      { line: 334, code: "", note: '空行' },
      { line: 335, code: ".m3-code-line__code {", note: '代码 pre 块' },
      { line: 336, code: "  margin: 0;", note: '去掉默认 margin' },
      { line: 337, code: "  overflow-x: auto;", note: '代码过长横向滚动' },
      { line: 338, code: "  -webkit-overflow-scrolling: touch;", note: 'iOS 横向惯性滚动' },
      { line: 339, code: "}", note: 'pre 结束' },
      { line: 340, code: "", note: '空行' },
      { line: 341, code: ".m3-code-line__code code {", note: 'pre 内 code 元素' },
      { line: 342, code: "  font: 400 11px/18px ui-monospace, SFMono-Regular, Menlo, monospace;", note: '等宽 11px 源码字体' },
      { line: 343, code: "  color: var(--md-sys-color-on-surface);", note: '主文字色' },
      { line: 344, code: "  white-space: pre;", note: '保留空格与换行（pre 排版）' },
      { line: 345, code: "}", note: 'code 结束' },
      { line: 346, code: "", note: '空行' },
      { line: 347, code: ".m3-code-line__note {", note: '每行下方中文备注' },
      { line: 348, code: "  margin: 6px 0 0;", note: '与代码区间距 6px' },
      { line: 349, code: "  padding-left: calc(2.5rem + 8px);", note: '左缩进与代码列对齐（行号宽 + gap）' },
      { line: 350, code: "  font-size: 12px;", note: '备注字号 12px' },
      { line: 351, code: "  line-height: 17px;", note: '备注行高 17px' },
      { line: 352, code: "  color: var(--md-sys-color-on-surface-variant);", note: '次要灰色说明文字' },
      { line: 353, code: "}", note: 'note 结束' },
      { line: 354, code: "", note: '空行' },
      { line: 355, code: "@media (min-width: 600px) {", note: '平板/桌面断点（代码样式之后，行号已更新）' },
      { line: 356, code: "  .m3-sheet-panel {", note: '大屏下面板不再全宽' },
      { line: 357, code: "    left: 50%;", note: '先移到中间' },
      { line: 358, code: "    right: auto;", note: '取消右贴边' },
      { line: 359, code: "    width: min(100%, 480px);", note: '最大宽 480px' },
      { line: 360, code: "    transform: translate(-50%, 100%);", note: '水平居中 + 藏在底部' },
      { line: 361, code: "  }", note: '大屏 panel 基础态结束' },
      { line: 362, code: "", note: '空行' },
      { line: 363, code: "  .m3-sheet-root.is-open .m3-sheet-panel {", note: '大屏打开态' },
      { line: 364, code: "    transform: translate(-50%, var(--sheet-drag-offset, 0px));", note: '居中显示并支持拖拽偏移' },
      { line: 365, code: "  }", note: '大屏 open 结束' },
      { line: 366, code: "", note: '空行' },
      { line: 367, code: "  .m3-sheet-panel.is-closing {", note: '大屏关闭态' },
      { line: 368, code: "    transform: translate(-50%, 100%) !important;", note: '居中前提下收回底部' },
      { line: 369, code: "  }", note: '大屏 closing 结束' },
      { line: 370, code: "}", note: '媒体查询结束' }
    ],
  },
]
